connpassイベント一覧用のfunctionsを作成
firebasejp/old-app pull request #6
Opened 2019-07-21 14:18 UTC by Kesin11

fix #5 

# 概要
connpassのAPIの内容をfirestoreの`events/`に保存します。

将来的にconnpass以外のイベントソースに対応できるように`Events`のインターフェースはconnpass以外のサイトのAPIレスポンスも参考にしました。といっても、どこもconnpassのレスポンスとほぼ大差はなかったのでイベントの情報としてはこんなもので十分なのではないかと。

https://www.doorkeeper.jp/developer/api?locale=en
https://api.atnd.org/

# 動作確認
`functions.pubsub.schedule`に変更する前に`npm run shell`でデバッグしようと思ったのですが、よくわからないエラーで実行できなかったのでできていないです・・・
このissueを踏んでいるっぽい？
https://github.com/firebase/firebase-tools/issues/ 1451

これが自分の環境依存の問題かどうか切り分けられなかったので、ちょっと試してみて欲しいです

2019-07-21 14:25 UTC, Kesin11 commented
functionsの中身のロジックだけ別のファイルに移してデバッグしてみたのですが、そこでも謎な現象が。
なぜかfirejpug-devのfirestoreではなく、自分がプライベートで使ってる方のfirestoreに書き込まれてしまいました。
`firestore list`の結果ではcurrentは間違いなくfirejpug-devになっているのですけどね。。

一応、書き込まれた内容自体は意図したものになってました

```js
import * as admin from 'firebase-admin'
import { ConnpassClient } from './client/connpass'
import { FirestoreSimple } from 'firestore-simple'
import { ConnpassEvent, Event } from './model/event'

const app = admin.initializeApp()
const firestore = app.firestore()
const firestoreSimple = new FirestoreSimple(firestore)

const main = async () => {
  const eventsCollection = firestoreSimple.collection<Event>({ path: 'events' })

  const client = new ConnpassClient()
  const apiResponse = await client.fetch()
  const events = apiResponse.map((responseEvent) => new ConnpassEvent(responseEvent))

  await eventsCollection.bulkSet(events)
}

main().catch((err) => { console.error(err)})
```

2019-07-21 17:27 UTC, k2wanko requested changes

2019-07-21 17:27 UTC, k2wanko commented on functions/src/model/event.ts
> +  eventId: number, // 各サービス内でのevent_id
`id` があるなら `eventId` は必要ないかな。
アプリ内ではブラウザでイベントページを開くだけなので `eventId` を使うことがない

2019-07-21 17:27 UTC, k2wanko commented on functions/src/model/event.ts
> +  catch: string, // キャッチ
`catch` は僕的にはあんまりいらないかなー、普段からそんなに設定してないので。

2019-07-21 17:27 UTC, k2wanko commented on functions/src/model/event.ts
> +  startedAt: Date, // 開始時間
好みの問題なんだけど `At` なしで `started` だけのがいいです。

2019-07-21 17:27 UTC, k2wanko commented on functions/src/model/event.ts
> +  endedAt: Date, // 終了時間
`startedAt` と同じ

2019-07-21 17:27 UTC, k2wanko commented on functions/src/model/event.ts
> +  updatedAt: Date, // 更新日時
`startedAt` と同じ

2019-07-21 17:27 UTC, k2wanko commented on functions/tslint.json
> +{
余力があればeslintに置き換えてほしいです。

2019-07-22 03:52 UTC, k2wanko requested changes

2019-07-22 03:52 UTC, k2wanko commented on functions/src/client/connpass.ts
> +        series_id: 4070
Osakaのも取得したいので引数で設定できるようにしてください。

2019-07-22 12:12 UTC, Kesin11 commented on functions/src/model/event.ts
> +  startedAt: Date, // 開始時間
OKです。
昔、perlかrubyあたりで_atだったらtimestampのINTからDateオブジェクトに変換するみたいなコードを見た記憶はありますが、TypeScriptで型はきっちり扱うし同感です

2019-07-22 12:13 UTC, Kesin11 commented on functions/tslint.json
> +{
暇になってしまったら別のpull-reqでやっておこうかと思います

2019-07-22 12:20 UTC, Kesin11 commented on functions/src/client/connpass.ts
> +        series_id: 4070
memo:
osakaのseries_idは6629

2019-07-22 12:23 UTC, Kesin11 commented on functions/src/client/connpass.ts
> +        series_id: 4070
ちなみに、今はcronでtokyoしか取得していないですがosakaの方も一緒にfirestoreに入れるように直しておきますか？

2019-07-22 12:40 UTC, Kesin11 commented
Firestoreに入ったデータを見たらいくつか型ミスってるな・・・

2019-07-22 21:35 UTC, k2wanko requested changes

2019-07-22 21:35 UTC, k2wanko commented on functions/src/model/event.ts
> +  lon: string, // 軽度 浮動小数点の丸め誤差防止のためにstring
@Kesin11 
緯度、軽度ってFirestoreの Geographical pointで保存できないですかね？

2019-07-24 15:03 UTC, Kesin11 commented on functions/src/model/event.ts
> +  lon: string, // 軽度 浮動小数点の丸め誤差防止のためにstring
割と簡単に対応できたので修正しました

2019-07-27 09:46 UTC, k2wanko approved these changes

2019-07-27 09:46 UTC, merged